### ISSUE TITLE
utils.py missing

### ISSUE THREAD

**Issue by ddomingof** [omicsNLP/MetaboliteNER#1]
There are several methods missing:

`sobie_scores_to_char_ents`

`post_process`

I guess they are in `utils.py`. Could you please verify the script is not missing?

**Comment by jmp111** [comment]
@ddomingof I've added the missing file. @cheng-yeung can confirm if this is the latest version.

**Comment by ddomingof** [comment]
`f = open(_getpath("words.txt"), "r",`

This file is missing still :)

**Comment by ddomingof** [comment]
`tabolistem` also seems to be missing all related files
- `./TrainedModels/tabolistem_%s.json`
- ...

**Comment by ddomingof** [comment]
If you want, I can refactor you the code to make it more reproducible but I need the files to be able to run it.
Maybe it would be nice to put all static files into a different folder and create a constants.py where all the files are pointed to in Python instead of hard coded

**Comment by jmp111** [comment]
(Just for completeness as we discussed this via email)

> `tabolistem` also seems to be missing all related files
> 
> * `./TrainedModels/tabolistem_%s.json`
> * ...

This can be found here: https://bitbucket.org/rscapplications/chemlistem/src/master/chemlistem/words.txt

> `tabolistem` also seems to be missing all related files
> 
> * `./TrainedModels/tabolistem_%s.json`
> * ...

I have uploaded this (and other files) to Zenodo at this doi for the BERT-embedding TABoLiSTM model: https://doi.org/10.5281/zenodo.6340002
